[package]
name = "decentralized-p2p-streaming-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
prost = "0.12"

[build-dependencies]
prost-build = "0.12"
